name: Update README.md
on:
  schedule:
    # 평일 오전 9시마다 액션을 실행한다.
    - cron: "0 0 * * 1-5"

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: "Install NodeJS ${{ matrix.node-version }}"
        uses: actions/setup-node@v1.4.5
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Update README.md
        run: |
          cd tasks
          npm ci
          npm run start
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add ../README.md
          git add ./data/solved.json
          git commit -m "Update README.md"
          git push origin main
